resources:
- repo: self

trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
      - '*'

jobs:
- job: TestAzureCLITask
  displayName: Test Azure CLI Task

  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    displayName: Azure CLI
    inputs:
      azureSubscription: service-connection-test1
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -vx
        ls ~/.azure
        cat ~/.azure/versionCheck.json
        cat ~/.azure/accessTokens.json

        echo $AZURE_CONFIG_DIR
        ls $AZURE_CONFIG_DIR
        cat $AZURE_CONFIG_DIR/versionCheck.json
        cat $AZURE_CONFIG_DIR/accessTokens.json

        az group list
