# Azure DevOps task for automation test using azdev and pytest

parameters:
- name: pythonVersion
  type: string
  default: ''
- name: profile
  type: string
  default: ''
- name: fullTest
  displayName: 'Run full test?'
  type: boolean
  default: false

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}
      displayName: "Use Python ${{ parameters.pythonVersion }}"
  - template: ./azdev_setup.yml
  - bash: |
      set -ev

      source env/bin/activate

      echo pythonVersion: ${{ parameters.pythonVersion }}
      echo profile: ${{ parameters.profile }}
      echo fullTest: ${{ parameters.fullTest }}
      echo Build.Reason: $(Build.Reason)

      pytest src/azure-cli-core/azure/cli/core/tests/test_profile.py -n 2 --forked -vvv
    displayName: "Test on Profile ${{ parameters.profile }}"
    env:
      ADO_PULL_REQUEST_LATEST_COMMIT: $(System.PullRequest.TargetBranch)
